name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt file found. Skipping dependency installation."
          fi

      - name: Prepare for local deployment
        run: |
          echo "Preparing project for local execution..."
          zip -r project.zip .  # Zip the project for local use
          echo "Project ready for local deployment!"