name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          # Force full validation (avoids Git diff issues)
          VALIDATE_ALL_CODEBASE: "true"
          # Disable "only changed files" mode
          VALIDATE_ONLY_CHANGED_FILES: "false"
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}