name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt file found. Skipping dependency installation."
          fi

      - name: Run Python tests
        run: |
          python -m pytest --ignore=Sign-Sync/backend/alphabetTranslate-service/image-cnn/scripts/test_asl_model.py
          
          if [ -d "Sign-Sync/__tests__" ]; then
            python -m pytest Sign-Sync/__tests__/
          else
            echo "No tests directory found. Skipping Python tests."
          fi
          
          # python -m pytest Sign-Sync/backend/alphabetTranslate-service/alphabetTranslate_unitTests.py
          # python -m pytest Sign-Sync/backend/alphabetTranslate-service/alphabetTranslate_integrationTests.py
          
          python -m pytest Sign-Sync/backend/gestureRecognition-service/tests/integration.py
          python -m pytest Sign-Sync/backend/gestureRecognition-service/tests/test.py
          python -m pytest Sign-Sync/backend/gestureRecognition-service/tests/unit.py
          
          python -m pytest Sign-Sync/backend/speechToText-service/unitTesting/unitTests.py
          python -m pytest Sign-Sync/backend/speechToText-service/speechToText_integrationTests.py
          python -m pytest Sign-Sync/backend/speechToText-service/speechToText_unitTests.py

          python -m pytest Sign-Sync/backend/tests/unitTests.py

          python -m pytest Sign-Sync/backend/textToAslGloss-service/glossCoversion_integrationTests.py
          python -m pytest Sign-Sync/backend/textToAslGloss-service/glossCoversion_unitTests.py
          
      # - name: Install node dependencies
      #   run: npm install
      #   working-directory: ./Sign-Sync

      # - name: Run Rejex tests
      #   run: npm test
      #   working-directory: ./Sign-Sync
      #   timeout-minutes: 1
